piVersion: ahora.dev/v1alpha1
kind: SPA
metadata:
  name: example-spa
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  SPAArchiveURL: https://storage.googleapis.com/ahora-spa-archives/spa-demo.tar.gz
  replicas: 2
  hosts: 
  - www.example.com
  - example.com
  tls:
  - secretName: example-ssl
    hosts:
    - www.example.com
    - example.com
  livenessProbe:
    httpGet:
      path: /status
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /status
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
  paths:
  - path: /api
    backend:
      serviceName: backendservice
      servicePort: 80